version: "2"
services:
   namenode:
      image: hadoop  # or use 'image: hadoop3' in case you built the images locally
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: hadoop  # or use 'image: hadoop3' in case you built the images locally
      command: ["hdfs", "datanode"]
      env_file:
        - ./config      
   resourcemanager:
      image: hadoop  # or use 'image: hadoop3' in case you built the images locally
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager:
      image: hadoop
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
